apiVersion: apps/v1
kind: Deployment
metadata:
  name: student
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student
  template:
    metadata:
      labels:
        app: student
    spec:
      containers:
        - name: app
          image: achrefby/devops:latest 
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo-service:27017/gte3
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: student
spec:
  selector:
    app: student
  ports:
    - port: 8090
      targetPort: 8090
  type: NodePort